name: Deploy to Hostinger via SSH

on:
  push:
    branches: [ "main" ]   # ganti jika deploy dari branch lain
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Prepare rsync exclude
        run: |
          cat > .rsync-exclude << 'EOF'
          .git/
          .github/
          node_modules/
          vendor/
          tests/
          storage/logs/**
          storage/framework/cache/data/**
          storage/*.key
          .env
          **/*.env
          EOF

      - name: Rsync source to server
        run: |
          rsync -az --delete \
            -e "ssh -p ${{ secrets.HOSTINGER_PORT }} -o StrictHostKeyChecking=no" \
            --exclude-from=.rsync-exclude \
            ./ ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:${{ secrets.HOSTINGER_PATH }}/

      - name: Remote deploy steps
        run: |
          ssh -p ${{ secrets.HOSTINGER_PORT }} -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} << 'EOF'
          set -e
          cd ${{ secrets.HOSTINGER_PATH }}

          # OPTIONAL: maintenance mode saat deploy
          # php artisan down --render="errors::maintenance" || true

          # Install dependencies TANPA composer scripts (hindari pre/post script errors)
          if command -v composer >/dev/null 2>&1; then
            COMPOSER_ALLOW_SUPERUSER=1 COMPOSER_MEMORY_LIMIT=-1 \
            composer install --no-dev --optimize-autoloader --no-interaction --no-progress --prefer-dist --no-scripts
          else
            echo "Composer not found on server. Consider building vendor in CI dan upload."
          fi

          # Laravel housekeeping (manual, pengganti composer scripts)
          php artisan package:discover --ansi || true
          php artisan migrate --force || true

          chmod -R 775 storage bootstrap/cache || true

          # php artisan up || true
          EOF
